### ISSUE TITLE
Add GitHub Support

### ISSUE THREAD

**Issue by Jakub-Vacek** [DXHeroes/Pipeliner#1]
Add `GitHubService` which implements `IService` protocol and implement it's functions. You can use [GitHub Checks API](https://docs.github.com/en/rest/reference/checks#get-a-check-run).

**Comment by czuria1** [comment]
Hello! I'm interested in working on this issue 🙂

**Comment by Jakub-Vacek** [comment]
Hi! Great 👍 If you have any questions feel free to contact me 🙂

**Comment by czuria1** [comment]
Hi @Jakub-Vacek! Since the Checks API seems to only allow getting a single check run given an id. Will the update to the UI for the user to input the check_run_id b supposed to be done in #6 or will this be the projectId? Or should I be looking elsewhere to display several pipelines?
