### ISSUE TITLE
Add icons for each version control service

### ISSUE THREAD

**Issue by Jakub-Vacek** [DXHeroes/Pipeliner#10]
Each version control service has its logo. Logo is displayed in configuration and pipeline list next to repository name.
Depends on [#6](https://github.com/DXHeroes/Pipeliner/issues/6)

**Comment by kucharzykt** [comment]
**Hello, I tried to create a pull request to fix this issue, but I am not able to create a pull request from my commit. Until i will figure it out here is my text for pull request:**

**Add icons for each version control service #10**

**Version control service icons added to:**

- [X]  Configuration Picker (1)
- [X] Saved configuration (2)
- [X] Pipelines in Pipeliner app (3)
- [X] Pipelines in Pipeliner Widget - small, medium and large (4)

Visible on the screenshots below.

![pipeliner_icons_added](https://user-images.githubusercontent.com/23358122/101082867-7647dc00-35ac-11eb-8b6c-5f93aff15bc5.png)

GitHub icon was not standing out in dark mode so I added black and also white icon. Light mode uses black and dark mode uses white icon. 

![pipeliner_light_mode_github](https://user-images.githubusercontent.com/23358122/101082910-86f85200-35ac-11eb-9ca3-4912ebae635e.png)

I added also Bitbucket option for the future, it is commented for now.

All the icons are from official assets(company websites), sized down to 18x18.png files. I don’t know how to resize NSImage, so after some time I resized the icons. If there is some simple solution I will be very happy to learn about it.  
⚠️I had to add assets into build phases for Pipeliner and PipelinerWidget to be able to load the icons. **It is not commited** in github

![assets_build_phases_pipeliner](https://user-images.githubusercontent.com/23358122/101082958-95df0480-35ac-11eb-960a-815aac8791ab.png)
![assets_build_phases_widget](https://user-images.githubusercontent.com/23358122/101082963-96779b00-35ac-11eb-8f72-40ae975ccb44.png)

I also added serviceType to PipelineResult, so I can load icon according to type for widget pipelines.

I hope that this changes will be useful.

BR,
Tom.

**Comment by Jakub-Vacek** [comment]
Hi 👋 Great job 👍I like white & black logo detail 🙂I can see png icons in Assets.xcaassets folder which I fine. Also i think you committed some of yours user data`.../project.xcworkspace/xcuserdata/tomaskucharzyk.xcuserdatad/UserInterfaceState.xcuserstate` which is unnecessary. Otherwise your PR is fine.

**Comment by kucharzykt** [comment]
Thank you 🙂 should i remove the file? Or it is okay and i can leave it there?
