### ISSUE TITLE
Add in progress pipeline state 

### ISSUE THREAD

**Issue by Jakub-Vacek** [DXHeroes/Pipeliner#27]

**Comment by kucharzykt** [comment]
Hello, I would like to fix this issue.
This is my first time contribution on GitHub. 
I will create a pull request, I simply added missing status according to GitLab documentation.

There is also new icon and status label for status that is nor success nor error. 
I will be very grateful for any feedback.

<img width="1335" alt="pipeliner_small_widget" src="https://user-images.githubusercontent.com/23358122/100659417-e65a2600-3350-11eb-9aad-e240dc99aae5.png">
<img width="528" alt="medium_widget" src="https://user-images.githubusercontent.com/23358122/100659427-e9551680-3350-11eb-8ad0-fe7e617d7172.png">
