### ISSUE TITLE
Improve TextField description for GitLab UI

### ISSUE THREAD

**Issue by Jakub-Vacek** [DXHeroes/Pipeliner#3]
Rename `Base Url` parameter and provide tooltip description or url link (under question mark icon - same as `Private Access Token` parameter)

**Comment by rarcilla** [comment]
Hello! I'm interested in working on this issue - I'm new to OSS but have Swift and a little bit of SwiftUI experience!

**Comment by Jakub-Vacek** [comment]
Hello! Sure! Go ahead 👍 If you have any questions feel free to connect me. 🙂

**Comment by DominikMilaniak** [comment]
**Hi** @rarcilla! 🙂 

A few days have passed since our last contact, how is it going so far with the issue? Is anything not clear enough or do you need help with something? I am in no way pushing you, you can take as much time as you need 🙂  Just wanted to get in touch to make sure everything is ok and you have enough information 👍

**Comment by rarcilla** [comment]
@DominikMilaniak Hi there, thanks so much for checking in! :) I haven't gotten around to downloading big sur beta so I haven't yet explored the codebase, but I'm planning to do so over the next couple of days. In the meantime, it'd be great if I could get more context on the issue description, specifically, what to rename the base URL parameter to, and what "same as Private Access Token parameter" means.

**Comment by Jakub-Vacek** [comment]
Hi 👋 Name of the parameter is up to you 🙂 `Base Url` is fine for developers but for other people could be better more general `Web Address`. How would you call this kind of parameter?

There is a question mark next to `Private Access Token` label which leads to GitLab docs covering access token. Goal is to add something similar to `Base Url` parameter - it can be url leading to some trustworthy docs (GitLab, GitHub) or it can be image which shows what is meant by that parameter. 

I don't think that you will face any issues (project doesn't have any special setup). But we are talking about beta developer IDE so..😁

**Comment by rarcilla** [comment]
@Jakub-Vacek Got it. Thank you for clarifying! I will get started 😄

**Comment by rarcilla** [comment]
Hi!! Sorry to bother with another question.

So my project is building without errors now after following instructions from one of the issue threads, but when I try running the Pipeliner app on My Mac, its crashes immediately. However, the widget extension looks like it's running fine! Do you have any suggestions to fix this?

**Comment by Jakub-Vacek** [comment]
Sorry to hear that 😞Do you get any runtime error?

**Comment by rarcilla** [comment]
No, I don't see any runtime errors either.. not sure what I'm missing in the installation process that's causing this. I'll refork the latest version and try again. Once I get this sorted out, I would love to update the contributing page with this extra information I gathered from running into setup problems 😅

**Comment by Jakub-Vacek** [comment]
I just tested setup master on my device and it works 🤷 You read my mind! We talked about it yesterday with my colleagues😁Great idea👍

**Comment by rarcilla** [comment]
So I noticed something interesting when I edit the scheme: when I uncheck the "Debug executable" button in the Pipeliner scheme, it seems to launch the app properly (aside from a User Defaults message in the console). Is this how your scheme is setup as well, or should it be turned on at all times?

![Screen Shot 2020-10-20 at 9 18 54 PM](https://user-images.githubusercontent.com/45868050/96672864-122dc900-131a-11eb-901b-0a4a76096d82.png)

When it is checked this is what happens:
![Screen Shot 2020-10-20 at 9 25 35 PM](https://user-images.githubusercontent.com/45868050/96673217-da735100-131a-11eb-886c-440f7f18d508.png)

**Comment by Jakub-Vacek** [comment]
Hi 👋 I have this option checked. It almost looks like there can be bug in Xcode debug tool. 🤯 This is interesting, i would probably turn it off for now, and try google for similar issues with debug.

**Comment by rarcilla** [comment]
Hi! You're right, it was an Xcode issue! I came across a Twitter thread and found that it was specifically affecting macOS apps running Xcode 12.2 beta. I toggled "Debug Process as root" in Pipeliner's Run Scheme, and it's working now! https://developer.apple.com/forums/thread/663823 

Thanks for your help! 😄
