### ISSUE TITLE
Add GitHub configuration UI

### ISSUE THREAD

**Issue by Jakub-Vacek** [DXHeroes/Pipeliner#4]
Add UI for setting GitHub configuration to pipeliner `ContentView` file. User can choose service (GitLab, GitHub, BitBucket) using Swift UI `Picker`.  After choosing GitHub user can enter configuration for this type of service. Every `TextField` should have clear label. Optionally label can contain `Link` to online description (same as GitLab token `TextField`)

Depends on [#1](https://github.com/DXHeroes/Pipeliner/issues/1)

**Comment by czuria1** [comment]
I would like to work on this issue next, of course if the work for #1 looks good
