### ISSUE TITLE
Github web adress

### ISSUE THREAD

**Issue by aydenmrt** [DXHeroes/Pipeliner#43]
Where can I find my github web adress please ?

**Comment by zeman-j4** [comment]
Hello aydenmrt, your github address is https://github.com/aydenmrt - it is the link to your personal account.

Enjoy :)

**Comment by aydenmrt** [comment]
Hello, thank you , I thought that, but I always have an error message : 
The operation couldn’t be completed. (Pipeliner.ApiError error 0.)
